# Generated by Django 5.1.5 on 2025-02-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('degree', models.CharField(max_length=25)),
                ('passed_out_year', models.CharField(max_length=5)),
                ('emailid', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=10)),
            ],
        ),
    ]
