# Generated by Django 5.1.5 on 2025-02-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='roll_number',
            field=models.CharField(max_length=4),
        ),
    ]
