# Generated by Django 5.1.5 on 2025-02-03 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_students_roll_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
